#!/usr/bin/env python3
"""Emit an app-optimized data module from the normalized dataset.
Reads ../data/*.json, writes ../app/poe2_data.js -> window.POE2."""
import json, os, re, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
APP = os.path.join(HERE, "..", "app")

LINK_PIPE = re.compile(r"\[([^\]|]+)\|([^\]]+)\]")
LINK_PLAIN = re.compile(r"\[([^\]]+)\]")

def clean_text(t):
    t = LINK_PIPE.sub(r"\2", t or "")
    t = LINK_PLAIN.sub(r"\1", t)
    return t.replace("\n", " / ").strip()

def slim_mod(m):
    return {
        "id": m["id"], "name": m.get("name", ""), "text": clean_text(m.get("text", "")),
        "side": m.get("side"), "group": m.get("group", []), "ilvl": m.get("ilvl", 1),
        "tags": m.get("tags", []), "mtags": m.get("mtags", []),
        "essence_only": m.get("essence_only", False), "bw": m.get("bw", {}),
        "src": m.get("src", "base"),
    }

def main():
    classes = json.load(open(os.path.join(DATA, "poe2_mods_by_class.json")))
    bases_by_class = json.load(open(os.path.join(DATA, "poe2_bases.json")))
    ess_path = os.path.join(DATA, "poe2_essences.json")
    essences = json.load(open(ess_path))["essences"] if os.path.exists(ess_path) else []
    cat_path = os.path.join(DATA, "poe2_catalysts.json")
    catalysts = json.load(open(cat_path))["catalysts"] if os.path.exists(cat_path) else []
    imp_path = os.path.join(DATA, "poe2_implicits.json")
    implicits = json.load(open(imp_path))["byClass"] if os.path.exists(imp_path) else {}

    out = {}
    for ic, d in classes.items():
        bases = [{"name": b["name"], "tags": b["tags"], "drop_level": b["drop_level"]}
                 for b in bases_by_class.get(ic, [])]
        bases.sort(key=lambda b: (b["drop_level"], b["name"]))
        out[ic] = {
            "bases": bases,
            "prefixes": [slim_mod(m) for m in d["prefixes"]],
            "suffixes": [slim_mod(m) for m in d["suffixes"]],
            "desecrated": [slim_mod(m) for m in d.get("desecrated", [])],
        }

    os.makedirs(APP, exist_ok=True)
    payload = {
        "builtAt": datetime.datetime.utcnow().isoformat() + "Z",
        "patch": "0.5 (Return of the Ancients)",
        "classes": out, "essences": essences,
        "catalysts": catalysts, "implicits": implicits,
    }
    js = "// Auto-generated by build_app_data.py. Do not edit by hand.\n"
    js += "window.POE2 = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    path = os.path.join(APP, "poe2_data.js")
    open(path, "w").write(js)
    kb = os.path.getsize(path) // 1024
    print(f"Wrote {path} ({kb} KB), {len(out)} classes, {len(essences)} essences, "
          f"{len(catalysts)} catalysts, {sum(len(v) for v in implicits.values())} implicit-bases")

if __name__ == "__main__":
    main()
